name: Deploy
on:
  workflow_dispatch: {}
  push:
    branches:
      - main
jobs:
  deploy-staging:
    environment: staging
    name: Deploy to staging
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only --ha=false
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  inspect-staging:
    environment: staging
    name: Inspect staging deploy
    runs-on: ubuntu-latest
    needs: deploy-staging
    steps:
      - run: |
          curl https://api.honeycomb.io/1/query_results/testinprodorlivealie \
          -X POST \
          -H "X-Honeycomb-Team: ${{ secrets.HONEYCOMB_API_KEY }}" \
          -d '{"query_id":"5vQuRshh5wN"}' | yq '.id | "QUERY_RESULT_ID="+.' >> "$GITHUB_ENV"
      - id: count-failed-requests
        run: |
          curl https://api.honeycomb.io/1/query_results/testinprodorlivealie/${QUERY_RESULT_ID} \
          -X GET \
          -H "X-Honeycomb-Team: ${{ secrets.HONEYCOMB_API_KEY}}" | yq '.data.results[0].data.COUNT | "failure-request-count="+.' >> "$GITHUB_OUTPUT"
      - name: Failure inspection (zero tolerance)
        if: steps.count-failed-requests.output.failure-request-count > 0
        run: |
            echo "::error failure_request_count=${{ steps.count-failed-requests.output.failure-request-count }}::{message}"
            exit 1
