name: Deploy
on:
  workflow_dispatch: {}
  push:
    branches:
      - main
jobs:
  deploy-staging:
    environment: staging
    name: Deploy to staging
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only --ha=false
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  inspect-staging:
    environment: staging
    name: Inspect staging deploy
    runs-on: ubuntu-latest
    needs: deploy-staging
    steps:
      - run: |
          curl https://api.honeycomb.io/1/query_results/testinprodorlivealie \
          -D- \
          -X POST \
          -H "X-Honeycomb-Team: ${{ secrets.HONEYCOMB_API_KEY }}" \
          -d '{"query_id":"5vQuRshh5wN"}' | tee - | yq '.id | "QUERY_RESULT_ID="+.' >> "$GITHUB_ENV"
      - run: |
          curl https://api.honeycomb.io/1/query_results/testinprodorlivealie/${QUERY_RESULT_ID} \
          -D- \
          -X GET \
          -H "X-Honeycomb-Team: ${{ secrets.HONEYCOMB_API_KEY}}" | tee - | yq '.data.results[0].data.COUNT | "FAILURE_REQUEST_COUNT="+.' >> "$GITHUB_ENV"
      - name: Failure inspection (zero tolerance)
        if: ${{ env.FAILURE_REQUEST_COUNT }} > 0
        run: |
            echo "::error failure_request_count=${{ env.FAILURE_REQUEST_COUNT }}::{message}"
            exit 1
